---
# tasks file for disk
- name: format disk
  shell: 'mkfs.{{ DISK_FSTYPE }} -F -L {{ DISK_MOUNT_DIR }} /dev/{{ DISK_DEV }}'

- name: make mount node
  shell: 'rm -rf /{{ DISK_MOUNT_DIR }} && mkdir /{{ DISK_MOUNT_DIR }}'

- name: update fstab
  lineinfile: dest=/etc/fstab line="LABEL={{ DISK_MOUNT_DIR }}             /{{ DISK_MOUNT_DIR }}     {{ DISK_FSTYPE }}    defaults,noatime,nodiratime        0 0"

- name: mount disk
  shell: 'mount -a'
